/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/biens/': RouteRecordInfo<
      '/biens/',
      '/biens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/biens/[id]': RouteRecordInfo<
      '/biens/[id]',
      '/biens/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/biens/create': RouteRecordInfo<
      '/biens/create',
      '/biens/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contrats/': RouteRecordInfo<
      '/contrats/',
      '/contrats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contrats/[id]': RouteRecordInfo<
      '/contrats/[id]',
      '/contrats/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/contrats/create': RouteRecordInfo<
      '/contrats/create',
      '/contrats/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/customers': RouteRecordInfo<
      '/customers',
      '/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inbox': RouteRecordInfo<
      '/inbox',
      '/inbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/locataires/': RouteRecordInfo<
      '/locataires/',
      '/locataires',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/locataires/[id]': RouteRecordInfo<
      '/locataires/[id]',
      '/locataires/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/locataires/create': RouteRecordInfo<
      '/locataires/create',
      '/locataires/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/'
      | '/settings/members'
      | '/settings/notifications'
      | '/settings/security'
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/members': RouteRecordInfo<
      '/settings/members',
      '/settings/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/security': RouteRecordInfo<
      '/settings/security',
      '/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/biens/index.vue': {
      routes:
        | '/biens/'
      views:
        | never
    }
    'src/pages/biens/[id].vue': {
      routes:
        | '/biens/[id]'
      views:
        | never
    }
    'src/pages/biens/create.vue': {
      routes:
        | '/biens/create'
      views:
        | never
    }
    'src/pages/contrats/index.vue': {
      routes:
        | '/contrats/'
      views:
        | never
    }
    'src/pages/contrats/[id].vue': {
      routes:
        | '/contrats/[id]'
      views:
        | never
    }
    'src/pages/contrats/create.vue': {
      routes:
        | '/contrats/create'
      views:
        | never
    }
    'src/pages/customers.vue': {
      routes:
        | '/customers'
      views:
        | never
    }
    'src/pages/inbox.vue': {
      routes:
        | '/inbox'
      views:
        | never
    }
    'src/pages/locataires/index.vue': {
      routes:
        | '/locataires/'
      views:
        | never
    }
    'src/pages/locataires/[id].vue': {
      routes:
        | '/locataires/[id]'
      views:
        | never
    }
    'src/pages/locataires/create.vue': {
      routes:
        | '/locataires/create'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/'
        | '/settings/members'
        | '/settings/notifications'
        | '/settings/security'
      views:
        | 'default'
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/members.vue': {
      routes:
        | '/settings/members'
      views:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
    }
    'src/pages/settings/security.vue': {
      routes:
        | '/settings/security'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
